jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Python script
        run: python3 main.py
